### ISSUE TITLE
Mobile toogler not working on events page.

### ISSUE THREAD

**Issue by spaceySama** [edcNITD-website/edcNITD-website#50]

**Comment by spaceySama** [comment]
Image of issue 
https://drive.google.com/file/d/1iRltSBrgS_90mxXPNi4Damjag-uahBc3/view?usp=drivesdk

https://drive.google.com/file/d/1ir_EpFL0itR4t5-QhfBLzix6qIOd3dSt/view?usp=drivesdk

**Comment by Prakhar19999** [comment]
@spaceySama This issue is resolved I guess?
